[project]
name = "nlight"
version = "1.11.0"
description = "Application for watching anime, reading manga/light novels."
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "authlib>=1.7.2",
    "beautifulsoup4>=4.13.5",
    "platformdirs>=4.7.1",
    "pyside6>=6.8.3",
    "pyside6-fluent-widgets>=1.8.7",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.39",
    "validators>=0.34.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
    "pyinstaller-versionfile>=3.1.0",
    "sort-requirements>=1.3.3",
]

[tool.ruff]
line-length = 79
extend-exclude = ["data"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ARG",
    "C4",
    "COM",
    "E",
    "EM",
    "ERA",
    "F",
    "FIX",
    "FURB",
    "G",
    "I",
    "ICN",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PLE",
    "PLW",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "T20",
    "TRY",
    "UP",
    "W",
]
extend-ignore = [
    "RUF001",
    "RUF002",
    "RUF003",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
order-by-type = false
known-first-party = [
    "nlightreader",
    "data",
    "keys",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true
