[tool.black]
line-length = 79
exclude = """
/(
  data/
  | venv/
  | build_nuitka/
  | nlight_res_rc.py
)
"""

[tool.flake8]
max-line-length = 79
inline-quotes = "double"
import-order-style = "google"
ignore = [
    "F401",
    "N802",
    "I100",
    "I202",
    "W503",
]
exclude = [
    "build",
    "build_nuitka",
    "dist",
    "venv",
    "data",
]