[tool.black]
line-length = 79
exclude = """
/(
  build/
  | build_nuitka/
  | data/
  | dist/
  | venv/
)
"""

[tool.flake8]
max-line-length = 79
inline-quotes = "double"
import-order-style = "pep8"
application-import-names = [
    "data",
    "nlightreader",
    "keys",
]
ignore = [
    "F401",
    "N802",
    "W503",
]
exclude = [
    "build",
    "build_nuitka",
    "data",
    "dist",
    "venv",
]